$(document).ready(function(){function l(f){f+="=";for(var h=decodeURIComponent(document.cookie).split(";"),b=0;b<h.length;b++){for(var a=h[b];" "==a.charAt(0);)a=a.substring(1);if(0==a.indexOf(f))return a.substring(f.length,a.length)}return""}function m(f,h){var b=$("div[id='"+f+"']");$("html,body").animate({scrollTop:b.offset().top+h},"slow")}(function(){$.ripple=function(f,h){var b=this,a=b.log=function(){b.defaults.debug&&console&&console.log&&console.log.apply(console,arguments)};b.selector=f;
b.defaults={debug:!1,on:"mousedown",opacity:.4,color:"auto",multi:!1,duration:.7,rate:function(k){return k},easing:"linear"};b.defaults=$.extend({},b.defaults,h);$(document).on(b.defaults.on,b.selector,function(k){var d=$(this);d.addClass("has-ripple");var c=$.extend({},b.defaults,d.data());if(c.multi||!c.multi&&0===d.find(".ripple").length){var g=$("<span></span>").addClass("ripple");g.appendTo(d);a("Create: Ripple");if(!g.height()&&!g.width()){var e=Math.max(d.outerWidth(),d.outerHeight());g.css({height:e,
width:e});a("Set: Ripple size")}c.rate&&"function"==typeof c.rate&&(e=Math.round(g.width()/c.duration),e=c.rate(e),e=g.width()/e,c.duration.toFixed(2)!==e.toFixed(2)&&(a("Update: Ripple Duration",{from:c.duration,to:e}),c.duration=e));e="auto"==c.color?d.css("color"):c.color;e={animationDuration:c.duration.toString()+"s",animationTimingFunction:c.easing,background:e,opacity:c.opacity};a("Set: Ripple CSS",e);g.css(e)}c.multi||(a("Set: Ripple Element"),g=d.find(".ripple"));a("Destroy: Ripple Animation");
g.removeClass("ripple-animate");e=k.pageX-d.offset().left-g.width()/2;k=k.pageY-d.offset().top-g.height()/2;c.multi&&(a("Set: Ripple animationend event"),g.one("animationend webkitAnimationEnd oanimationend MSAnimationEnd",function(){a("Note: Ripple animation ended");a("Destroy: Ripple");$(this).remove()}));a("Set: Ripple location");a("Set: Ripple animation");g.css({top:k+"px",left:e+"px"}).addClass("ripple-animate")})};$.ripple(".emu-ripple",{debug:!1,on:"mousedown",opacity:.5,color:"auto",multi:!1,
duration:.4,rate:function(f){return f},easing:"linear"})})();(function(){if($("#emugames_rating").length){var f=$("#emugames_rating").data("type"),h=$("#emugames_rating").data("id"),b=$("#emugames_rating").data("rate"),a="",k=!1;a=[];a=l(f+"_rating");if(""!=a){a=a.split("_");for(var d=0;d<a.length;d++)a[d]==h&&(k=!0)}$.getScript("https://cdn.emugames.net/resources/rate.min.js",function(){$("#emugames_rating").starRating({starSize:30,minRating:1,useFullStars:!0,emptyColor:"white",hoverColor:"gold",
activeColor:"#32ff6d",strokeWidth:2,strokeColor:"#666",starShape:"straight",useGradient:!1,initialRating:b,readOnly:k,callback:function(c,g){$.ajax({type:"POST",url:"/vote/",data:{get_type:f,get_id:h,get_rate:c},dataType:"json",cache:!1,success:function(e){$.get("/renew/",{url:window.location.href})},complete:function(){}})}})})}})();(function(){if($("#emugames_get").length){var f=$("#emugames_get").data("type"),h=$("#emugames_get").data("id"),b="",a='Your download has started!<span style="font-size:1.2em;">&nbsp;</span>',
k="error";$.ajax({type:"POST",url:"/download/",data:{get_type:f,get_id:h},dataType:"json",cache:!1,success:function(g){b=g[0];k=g[2];"error"==k&&(a='This request is not valid!<span style="font-size:1.2em;">&nbsp;</span>')},complete:function(){}});var d=4,c=setInterval(function(){0>=d&&(clearInterval(c),"success"==k&&($(document.body).append('<iframe style="display:none;" src="'+b+'"></iframe>'),"https://static.emugames.net"!=b&&""!=b&&setTimeout(function(){$("#emugames_get_manual").html('<br>Not working? <a rel="nofollow" href="'+
b+'">Click Here</a> to start download manually')},4E3)),setTimeout(function(){$("#emugames_get_notification").html(a)},800));$("#emugames_countdown").html(d);d--},1E3)}})();(function(){$("#emugames_game_box").length&&($("#emugames_game_box").append('<iframe name="emugames_game_area" id="emugames_game_area" style="display:none;"></iframe>'),$("#emugames_btn_play").click(function(){m("emugames_game_wrap",-20);$("#emugames_game_wrap").css({position:"relative",height:"480px",background:"#333","border-radius":"12px",
margin:"0 auto 16px auto"});$("#emugames_game_spinner").css({width:"80px",height:"80px","z-index":"2",position:"absolute","margin-left":"-40px","margin-top":"-40px",left:"50%",top:"50%"});$("#emugames_game_spinner").html('<div class="spinner-grow" style="width: 80px; height: 80px; background:#32ff6d;" role="status"></div>');setTimeout(function(){$("#emugames_game_spinner").hide();$("#emugames_game_area").css({display:"block",width:"100%",height:"480px",border:"0",background:"#333","border-radius":"12px"});
$("#emugames_game_area").attr({width:"100%",height:"480px",border:"0",frameborder:"0",scrolling:"no",allowfullscreen:"allowfullscreen"})},2E3)}))})();(function(){if($("#emugames_view").length){var f=$("#emugames_view").data("type"),h=$("#emugames_view").data("id");$.ajax({type:"POST",url:"/views/",data:{get_type:f,get_id:h},dataType:"json",cache:!1,success:function(b){},complete:function(){}})}})();(function(){$("#emugames_send_mail").length&&$("#emugames_send_mail").submit(function(f){$("#submit").addClass("disabled");
$("#submit").html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Sending...')})})()});